#Configuracoes do TimeTaker
#Wed Jun 17 19:53:22 BRT 2026
colorize.headings=true
default.dir=/home/paradigma0621/Documents
indent.headings=true
font.size=50
font.name=Monospaced
indent.spaces=5
window.height=1163
show.hidden=false
last.file=/home/paradigma0621/Documents/2026-06-16.md
word.wrap=false
window.width=2080
window.x=978
window.y=277
